### ─────────────────────────────────────────────────────────────
### 환경 변수 
@baseUrl = http://localhost:4000
@consumerEmail = consumer7@test.com
@consumerPassword = password123
@moverEmail = mover@example.com
@moverPassword = moverPw123!

# 테스트용 대상 드라이버 ID (DB에 실제 존재하는 DRIVER 사용자 ID)
@driverId = 98a33478-72bf-454c-a87b-008587c8b37d
@cookie = access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNmQxOTAyNS1jNzJlLTQxYTgtYmM3Zi0yMWNkOGZhMzA3MzYiLCJqdGkiOiI4NDk4Zjg3Ni01NzgxLTQ4MGQtODVkMS1kZDA3MGU1NzVmNDIiLCJyb2xlIjoiQ09OU1VNRVIiLCJpYXQiOjE3NjEyMDUwNjcsImV4cCI6MTc2MTIwNTk2NywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.sK7Y6lYyzLo3gWIP8OxgaZNp27YUGnqh4gfN3bZ4YS4;

### 좋아요 테스트(comsumer -> driver)
POST {{baseUrl}}/drivers/{{driverId}}/likes
Content-Type: application/json
Cookie:{{cookie}}

### 좋아요 취소 테스트(comsumer -> driver)
DELETE {{baseUrl}}/drivers/{{driverId}}/likes
Content-Type: application/json
Cookie:{{cookie}}

### 💙 내가 좋아요한 기사 목록 조회 (첫 페이지)
GET {{baseUrl}}/consumers/liked-drivers
Content-Type: application/json
Cookie:{{cookie}}

### 💙 좋아요한 기사 목록 (limit=5)
GET {{baseUrl}}/consumers/liked-drivers?limit=5
Content-Type: application/json
Cookie:{{cookie}}

###

### 💙 다음 페이지 (cursor 기반)
# 아래 cursor 값은 이전 응답의 nextCursor 값을 그대로 넣어 테스트
GET {{baseUrl}}/consumers/liked-drivers?limit=5&cursor=eyJsaWtlZEF0IjoiMjAyNS0xMC0xM1QwNjowMDowMC4wMDBaIiwiaWQiOiI4NDJhY2YtYTU5Mi00YWI4LTg4OTAtZTM1YmRiZDNlOTNlIn0=
Content-Type: application/json
Cookie:{{cookie}}