@host = http://localhost:4000


### 고객로그인
POST {{host}}/auth/signin
Content-Type: application/json

{
  "email": "login-test@test.com",
  "password": "password123",
  "role": "CONSUMER"
}

### 고객로그인 get api

GET  {{host}}/users/me
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTJlNGI3ZS0zYjJhLTQ1ODMtYmMxMS02Yzc4ZWMzMDgzMzYiLCJqdGkiOiJhZGZjN2UzMy05OTJmLTQxN2EtYmI2OS1mZjZjNmUxZTM5ZTgiLCJyb2xlIjoiQ09OU1VNRVIiLCJpYXQiOjE3NTkzMzE1MzYsImV4cCI6MTc1OTMzMjQzNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.F7bLYeFSwvynra_CLuAe3fK5N8GCyXXh_J6sKW9dkgY;

### 드라이버 로그인

POST {{host}}/auth/signin
Content-Type: application/json

{
  "email": "driver1@test.com",
  "password": "password1234",
  "role": "DRIVER"
}

### 드라이버 get api

GET  {{host}}/users/me
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTcyZDU4NC0xY2M1LTQ2YTgtYmYxMi04YTE1NmM4NmI1OWQiLCJqdGkiOiJkODI2ZGJkMy0zZDViLTQwOTItYTUxZC1kOTE2OWIxYTE1MjMiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzU5MzMxNTU3LCJleHAiOjE3NTkzMzI0NTcsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.dSxX2RuhgvU9JRpIjBIAvRJaIdJTEO5oJShj_xpnrDA;



### 실험중인거 고객id / 드라이버 쿠키

GET  {{host}}/users/9e2e4b7e-3b2a-4583-bc11-6c78ec308336
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTcyZDU4NC0xY2M1LTQ2YTgtYmYxMi04YTE1NmM4NmI1OWQiLCJqdGkiOiI3ZDFmMjFjMC0xMjA1LTQwMTItYWU0OS1kMzhlMGM4OWIxMDgiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzU5MjgwMjQzLCJleHAiOjE3NTkyODExNDMsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.iBkwCxLeZFLmExbg2XhlR9mEYgi1gaqr-Q1tk0mxCIA;

###

GET  {{host}}/users/2e72d584-1cc5-46a8-bf12-8a156c86b59d
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTJlNGI3ZS0zYjJhLTQ1ODMtYmMxMS02Yzc4ZWMzMDgzMzYiLCJqdGkiOiIzMDliYTFjNS0yNGM2LTQ4ZGMtOTIwZC1hMWYwNDk3ZDMxYWEiLCJyb2xlIjoiQ09OU1VNRVIiLCJpYXQiOjE3NTkyNzkwMTAsImV4cCI6MTc1OTI3OTkxMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.cQ1Yl8ItTV2akGuw6IYYSPqIue8QBw9zyIku64BnGPk;

### 유저 patch

PATCH {{host}}/users/me/profile
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTJlNGI3ZS0zYjJhLTQ1ODMtYmMxMS02Yzc4ZWMzMDgzMzYiLCJqdGkiOiJhYjUyZGZmYS00MzVlLTQxMWUtYmRlOC0zMTU1ZmVmYTgxNTgiLCJyb2xlIjoiQ09OU1VNRVIiLCJpYXQiOjE3NjAwNzI4NjEsImV4cCI6MTc2MDA3Mzc2MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.TGOyFtNbYoCfKHrO3fXaCes-hjXxI44fm1ByZNryt-k

{
  "currentPassword": "password1233",
  "newPassword": "password123"    
}


### 기사 받은 요청 조회
GET {{host}}/requests/received
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTcyZDU4NC0xY2M1LTQ2YTgtYmYxMi04YTE1NmM4NmI1OWQiLCJqdGkiOiI2ZWUyYWZkYy0xYTYzLTRhODEtOGFjZC0yM2U2MjQ1MTM4MDgiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzYwNDE0NTEwLCJleHAiOjE3NjA0MTU0MTAsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.dClQ_3V5lDxY7W0LQ2PJldmF7KBGXQjag2KcXpjXO3U