@host = http://localhost:4000


### 고객로그인
POST {{host}}/auth/signin
Content-Type: application/json

{
  "email": "test123123@test.com",
  "password": "password123",
  "role": "CONSUMER"
}

### 고객로그인 get api

GET  {{host}}/users/me
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTJlNGI3ZS0zYjJhLTQ1ODMtYmMxMS02Yzc4ZWMzMDgzMzYiLCJqdGkiOiJhZGZjN2UzMy05OTJmLTQxN2EtYmI2OS1mZjZjNmUxZTM5ZTgiLCJyb2xlIjoiQ09OU1VNRVIiLCJpYXQiOjE3NTkzMzE1MzYsImV4cCI6MTc1OTMzMjQzNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.F7bLYeFSwvynra_CLuAe3fK5N8GCyXXh_J6sKW9dkgY;

### 드라이버 로그인

POST {{host}}/auth/signin
Content-Type: application/json

{
  "email": "driverkim@test.com",
  "password": "driverkim123",
  "role": "DRIVER"
}

### 드라이버 get api

GET  {{host}}/users/me
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMDk0OTNjOS1mYTQzLTQyYTItODExOS1jNDAwNDUwYjkxYTMiLCJqdGkiOiIyMDBhMTJjNC01OWUwLTRiMjAtOTYzYy1kMjI2OGExZTU1YjMiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzYwODg4NjMwLCJleHAiOjE3NjA4ODk1MzAsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.0Qxa3OC0r-UoheMDQfC7HlHIZ_ps0eCg0JTyKkcueKk;



### 실험중인거 고객id / 드라이버 쿠키

GET  {{host}}/users/9e2e4b7e-3b2a-4583-bc11-6c78ec308336
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTcyZDU4NC0xY2M1LTQ2YTgtYmYxMi04YTE1NmM4NmI1OWQiLCJqdGkiOiI3ZDFmMjFjMC0xMjA1LTQwMTItYWU0OS1kMzhlMGM4OWIxMDgiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzU5MjgwMjQzLCJleHAiOjE3NTkyODExNDMsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.iBkwCxLeZFLmExbg2XhlR9mEYgi1gaqr-Q1tk0mxCIA;

###

GET  {{host}}/users/2e72d584-1cc5-46a8-bf12-8a156c86b59d
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTJlNGI3ZS0zYjJhLTQ1ODMtYmMxMS02Yzc4ZWMzMDgzMzYiLCJqdGkiOiIzMDliYTFjNS0yNGM2LTQ4ZGMtOTIwZC1hMWYwNDk3ZDMxYWEiLCJyb2xlIjoiQ09OU1VNRVIiLCJpYXQiOjE3NTkyNzkwMTAsImV4cCI6MTc1OTI3OTkxMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.cQ1Yl8ItTV2akGuw6IYYSPqIue8QBw9zyIku64BnGPk;

### 유저 patch

PATCH {{host}}/users/me/profile
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMDk0OTNjOS1mYTQzLTQyYTItODExOS1jNDAwNDUwYjkxYTMiLCJqdGkiOiIyMDBhMTJjNC01OWUwLTRiMjAtOTYzYy1kMjI2OGExZTU1YjMiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzYwODg4NjMwLCJleHAiOjE3NjA4ODk1MzAsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.0Qxa3OC0r-UoheMDQfC7HlHIZ_ps0eCg0JTyKkcueKk;

{
  "currentPassword": "password1234",
  "newPassword": "password123"    
}

### 
PATCH {{host}}/users/me/profile
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMDk0OTNjOS1mYTQzLTQyYTItODExOS1jNDAwNDUwYjkxYTMiLCJqdGkiOiIyMDBhMTJjNC01OWUwLTRiMjAtOTYzYy1kMjI2OGExZTU1YjMiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzYwODg4NjMwLCJleHAiOjE3NjA4ODk1MzAsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.0Qxa3OC0r-UoheMDQfC7HlHIZ_ps0eCg0JTyKkcueKk;

{
  "currentPassword": "password1234",
  "newPassword": "password123"    
}

### 기사 받은 요청 조회
GET {{host}}/requests/received
Content-Type: application/json
Cookie: Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMDk0OTNjOS1mYTQzLTQyYTItODExOS1jNDAwNDUwYjkxYTMiLCJqdGkiOiIyMDBhMTJjNC01OWUwLTRiMjAtOTYzYy1kMjI2OGExZTU1YjMiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzYwODg4NjMwLCJleHAiOjE3NjA4ODk1MzAsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.0Qxa3OC0r-UoheMDQfC7HlHIZ_ps0eCg0JTyKkcueKk;


### 기사 받은 요청 필터 조회
POST {{host}}/requests/received/search
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTcyZDU4NC0xY2M1LTQ2YTgtYmYxMi04YTE1NmM4NmI1OWQiLCJqdGkiOiIyMzE5YjYyMC04MGU2LTRmNTktYmFmOC05NTI3ZmVmOTNmY2YiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzYwNTAyNzAyLCJleHAiOjE3NjA1MDM2MDIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9._uT6GedN1ZbtXMyr4r1CE2FFyioJlgJwJ5rt6zXm9_s

{

}


### 카운팅
GET  {{host}}/requests/count
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTcyZDU4NC0xY2M1LTQ2YTgtYmYxMi04YTE1NmM4NmI1OWQiLCJqdGkiOiIzZWY4ZGVhNC1hOTVjLTQ4MjMtYWM4NS05ODIzMzc2YmRlNjQiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzYwNTA2ODg1LCJleHAiOjE3NjA1MDc3ODUsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.Zmvv4wg0jEtzmsc9jWhRpcnllYhXUcFr1B-_U4cgbTw


###
asdasd
asd
{
  "isInvited": false,
  "areas": ["SEOUL"],
  "serviceTypes": ["HOME_MOVE"],
  "consumerName": "김",
  "sortByMoveAt": "asc",
  "moveAtFrom": "2025-11-11T00:00:00.000Z",
  "moveAtTo": "2025-11-30T23:59:59.999Z"
}

{
  "isInvited": false,
  "serviceTypes": ["SMALL_MOVE"]
}


### 받은 요청거절
POST {{host}}/requests/reject
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZDM1M2I4NC1jYWQyLTRmNzYtYTAxOS05OTVhZDhiNDEyMmIiLCJqdGkiOiIyYjg2MmUxNy1hZTY3LTRmMTctYmVmMy0yOWM2MWVlOTk4N2YiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzYwOTM3MDkwLCJleHAiOjE3NjA5Mzc5OTAsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.oA9BS5cwtI3sq0Xv_BE4GUm8K65vO-gt5SEu9GkGZXc

{
  "requestId": "198fb801-4372-40ad-afbf-93e794521a91",
  "state": "REJECTED",
  "source": "GENERAL",
  "note": "테스트 거절"
}

### 리뷰 등록하기
POST {{host}}/reviews
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNmQxOTAyNS1jNzJlLTQxYTgtYmM3Zi0yMWNkOGZhMzA3MzYiLCJqdGkiOiI0OTk1MDBkMS1hMWE1LTRmMjAtOTNlNS04MTFhNzc4NmZmMWMiLCJyb2xlIjoiQ09OU1VNRVIiLCJpYXQiOjE3NjEwMDk1NDcsImV4cCI6MTc2MTAxMDQ0NywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.61dPNNVXVRRIMHGAFbG8_1Z1auSimXy-TTekSD23l18


{
  "rating": 5,
  "content": "기사님이 정말 친절하고 빠르게 도와주셨어요!",
  "quotationId": ""
}
// 보내지기는 하는데 생각해보면 현재 이렇게만 만들면 흠 의미없지않나 다시 로직생각해보기. POST로 이렇게보내면 거절인데
// 거기서 추가적으로 결과값으로 동작해야하는게 받은견적(요청)한 상태를 바꿔줘야한다.?
// 지금은 createDriverAction 여기에 그냥 만드는거 create 밖에안됨 추가적으로 해야됨 ㅇㅋ?










### 소비자 견적 요청 전체 조회
GET {{host}}/requests/list
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGVjMGI3MS1lZjQ2LTRkMDktOTExZC1jNTVhOWYzNjA1N2YiLCJqdGkiOiJkMDgwYjRkYi1kNjFlLTQxODgtOTVjZS03YjA2NDBhODIxMzEiLCJyb2xlIjoiQ09OU1VNRVIiLCJpYXQiOjE3NjE2MTg3OTcsImV4cCI6MTc2MTYxOTY5NywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.33frwlQ8P5K559hyZSTq59EcbNWtQT2YIcUfWJ6KvyU


### 견적 중복 요청 확인 API (고객)
GET {{host}}/requests/check
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1M2Q1YzgxMS0zZDAyLTRhOWMtYTNlOS01NDljYzM4Nzc2NzIiLCJqdGkiOiJlNGI3OTNiMy0zNDkyLTRkNGYtYjllOS05ZDI1ZmUyYmMyNjkiLCJyb2xlIjoiQ09OU1VNRVIiLCJpYXQiOjE3NjE1NTA3ODAsImV4cCI6MTc2MTU1MTY4MCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.fJ9VkmYjSWBEQ6OLWygeF6ArsNBpYzYoM9lQgE4xrgI

### 드라이버 견적 전체 조회
GET {{host}}/quotations
Content-Type: application/json
Cookie: __Host-access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZDM1M2I4NC1jYWQyLTRmNzYtYTAxOS05OTVhZDhiNDEyMmIiLCJqdGkiOiJmMjBhODFjMC1jMDgwLTRjNTktOTExYy01M2U3NmIyZTFjOWEiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzYxNjQzNTU1LCJleHAiOjE3NjE2NDQ0NTUsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.vJxk4hBLqOoNb3TlBpQX14ugTm6sy2H_WmewQiZuBGc



### 날씨
GET {{host}}/weather/current?city=Seoul
Content-Type: application/json

### 주간날씨
GET {{host}}/weather/forecast?city=Seoul&days=5
Content-Type: application/json